---
- name: Create a directory on the remote server
  hosts: all
  become: yes
  tasks:
    - name: Add Ondrej PHP repository
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx, PHP 7.4 and common PHP extensions
      ansible.builtin.apt:
        name:
          - nginx
          - php7.4-fpm
          - php7.4-mysql
          - php7.4-xml
          - php7.4-mbstring
          - php7.4-curl
          - php7.4-dom
          - php7.4-xmlrpc
          - php7.4-gd
        state: present

    - name: Clone a repository
      tasks:
        - name: Clone the private Git repository
          git:
            repo: "https://github.com/yusuffranklin/divistant-technical-test.git"
            dest: "/var/www/html/divistant-technical-test"
            version: "main"

    - name: Create Nginx vhost
      template:
        src: "nginx_vhost.conf.j2"
        dest: "/etc/nginx/sites-enabled/{{ repo_name }}.conf"

    - name: Delete default Nginx vhost
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      when: remove_default_nginx_vhost == true

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded