---
- name: Playbook for DB Server
  hosts: all
  become: yes
  tasks:
    - name: Update Apt
      ansible.builtin.apt:
        update_cache: yes

    - name: Install MySQL Server and Prometheus Node Exporter
      ansible.builtin.apt:
        name:
          - mysql-server
          - prometheus-node-exporter
        state: present

    - name: Start MySQL
      ansible.builtin.service:
        name: mysql
        state: started

    - name: Enable MySQL
      ansible.builtin.service:
        name: mysql
        enabled: yes

    - name: Create MySQL Configuration
      ansible.builtin.copy:
        src: "mysqld.cnf"
        dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
        owner: root
        group: root
        mode: 0744

    - name: Restart MySQL
      ansible.builtin.service:
        name: mysql
        state: restarted

    - name: Create Script and Backup Folder
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /root/scripts
        - /backup

    - name: Create Backup Script
      ansible.builtin.copy:
        src: "backup-db.sh"
        dest: "/root/scripts/backup-db.sh"
        owner: root
        group: root
        mode: 0755