---
- name: Playbook for Monitoring Server
  hosts: all
  become: yes
  tasks:
    - name: Install Prometheus
      ansible.builtin.apt:
        name:
          - prometheus
        state: present

    - name: Create Prometheus Configuration
      template:
        src: "prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"

    - name: Restart Prometheus
      service:
        name: prometheus
        state: restarted