global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.0.2:9100', '192.168.0.3:9100', '192.168.0.4:9100']
        labels:
          environment: "production"