---
- name: Playbook for Reverse Proxy Server
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx and Prometheus Node Exporter
      ansible.builtin.apt:
        name:
          - nginx
          - prometheus-node-exporter
        state: present

    - name: Create Nginx vhost
      ansible.builtin.copy:
        src: "reverse_proxy_nginx.conf"
        dest: "/etc/nginx/sites-enabled/app_server.conf"
        owner: root
        group: root
        mode: 0744

    - name: Delete default Nginx vhost
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      when: remove_default_nginx_vhost == true

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded