name: 'Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: production
    container:
      image: yusuffranklin/ansible:alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ansible Playbook to Reverse Proxy Server
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ansible-playbook --private-key private_key.pem -u root -i inventories/reverse-proxy/inventory.yaml playbooks/reverse-proxy-playbook.yaml

      - name: Ansible Playbook to App Server
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ansible-playbook --private-key private_key.pem -u root -i inventories/app-server/inventory.yaml playbooks/app-server-playbook.yaml